[package]
edition = "2021"
name = "resource-test"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[build-dependencies]
embed-resource = "1.7.3"
